name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Setup node cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: gulp build
      run: npx gulp build
      env:
        CI: true
    - name: gulp pack
      run: npx gulp pack
      env:
        CI: true
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: |
            ${{ github.workspace }}/dist/**/*.mcpack
            ${{ github.workspace }}/dist/**/*.mcaddon
