name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Setup node cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: npm install
      run: npm ci
      env:
        CI: true
    - name: npm test
      run: npm test
      env:
        CI: true
